### ISSUE TITLE
.sql database structure

### ISSUE THREAD

**Issue by tjfayaz120** [a4business/MPBX#4]
Hi, would you mind sharing the database structure for the tables? Would love to try this out thanks.

**Comment by a4business** [comment]
I would love to share database tables and stored procedures!  
   any time I am ready send it to every one who requested it.    
      via my website contact form:  a4business.com 
  or via aemail  :   george  at a4business.com

thank you for interest to my growing project!

**Comment by a4business** [comment]
DB structe is available now. 
 issue closed.
