### ISSUE TITLE
not able to install, asking for username and password

### ISSUE THREAD

**Issue by rccess** [a4business/MPBX#7]
hello team

i am not able to install, asking for username and password, it is asking password on downloading web UI

please do help

**Comment by rccess** [comment]
is this repo active ?

**Comment by rccess** [comment]
is this repo active ?

i am not able to install, asking for username and password, it is asking password on downloading web UI

**Comment by wouam31200** [comment]
Hi!
Same for me

```
 Install WEB GUI from repo [ enter ] 
Clonage dans './pbx'...
Username for 'https://git.a4business.com': 
```

**Comment by a4business** [comment]
Hi ,  
  Yes, this repo is  archived , 
   It a bit outdated  b/c  it moved to private git.
